name: CDTest-Hello-world
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Job1 CD Test Hello World!"
      - name: step2
        run: echo "Job1 Goodbye.."
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "Job2 CD Test Hello World!"
      - name: step2
        run: echo "Job2 Goodbye.."
